ALTER TABLE SCHEMA.TABLENAME ALTER COLUMN ColumnName varchar(10) NOT NULL;  
ALTER TABLE SCHEMA.TABLENAME ADD PRIMARY KEY (ColumnName);   
   
DROP INDEX IF EXISTS IX_SCHEMA_TABLENAME_ColumnName on SCHEMA.TABLENAME   
CREATE INDEX IX_SCHEMA_TABLENAME_ColumnName on SCHEMA.TABLENAME (ColumnName);   
